"""empty message

Revision ID: 3973f800e3d3
Revises: cf24052c98cd
Create Date: 2020-11-23 00:51:52.776477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3973f800e3d3'
down_revision = 'cf24052c98cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse', 'parentId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse', 'parentId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
