"""empty message

Revision ID: 410e56d4eac9
Revises: ecbe15928993
Create Date: 2020-11-08 16:05:38.318155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e56d4eac9'
down_revision = 'ecbe15928993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['verse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse')
    # ### end Alembic commands ###
