"""empty message

Revision ID: 77397c9d342e
Revises: 85ccb5d2c175
Create Date: 2020-11-14 20:44:32.648397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77397c9d342e'
down_revision = '85ccb5d2c175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['verse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse')
    # ### end Alembic commands ###
