"""empty message

Revision ID: 774be39a1536
Revises: d0190320a3c4
Create Date: 2020-11-14 20:59:34.939953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774be39a1536'
down_revision = 'd0190320a3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['verse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'parentId', name='_text_parent_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse')
    # ### end Alembic commands ###
