"""empty message

Revision ID: 85ccb5d2c175
Revises: 02cf926dae7b
Create Date: 2020-11-14 20:34:08.967030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ccb5d2c175'
down_revision = '02cf926dae7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse', 'parentId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('verse', 'text',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse', 'text',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('verse', 'parentId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
