"""empty message

Revision ID: cf24052c98cd
Revises: 14105ae149d6
Create Date: 2020-11-23 00:49:43.889910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf24052c98cd'
down_revision = '14105ae149d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse', 'parentId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verse', 'parentId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
