"""empty message

Revision ID: d8490f5f4b69
Revises: 3973f800e3d3
Create Date: 2020-11-23 00:57:49.516753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8490f5f4b69'
down_revision = '3973f800e3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['verse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'parentId', name='_text_parent_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse')
    # ### end Alembic commands ###
